- name: Add block of lines to /etc/hosts
  blockinfile:
    path: /etc/ssh/ssh_config
    block: |
      Host {{ gitlab_ip }}
          PasswordAuthentication yes
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          IdentityFile /root/.ssh/id_rsa
          IdentityFile {{ output_folder_gitrepo }}/tenant_repo_private.key
    state: present

- name: Git config
  shell: "git config --global user.email \"none@none.com\" &&  git config --global user.name \"none\" "

- name: Check dex client secret exists
  stat:
    path: "{{ output_folder_k8s }}/dex_client_secret"
  register: dex_client_secret_file

- name: Generate dex client secret
  copy:
    content: "{{ 1000000000 | random | to_uuid }}"
    dest: "{{ output_folder_k8s }}/dex_client_secret"
  when: not dex_client_secret_file.stat.exists

- set_fact:
    git_info: "{{ lookup('file', '{{ output_folder_gitrepo }}/infos.yaml' )|from_yaml }}"

- set_fact:
    ca_info: "{{ lookup('file', '{{ output_folder_pki }}/ca.crt' ) }}"
    gitlab_knowhost_rsa: "{{ lookup('file', '{{ output_folder_gitrepo }}/ssh_host_rsa_key.pub' ) }}"
    gitlab_knowhost_ecdsa: "{{ lookup('file', '{{ output_folder_gitrepo }}/ssh_host_ecdsa_key.pub' ) }}"
    gitlab_knowhost_ed25519: "{{ lookup('file', '{{ output_folder_gitrepo }}/ssh_host_ed25519_key.pub' ) }}"
    tenant_repo_id: "{{ git_info.tenant_repo_id }}"
    tenant_repo_ssh_addr: "{{ git_info.tenant_repo_ssh_addr }}"
    oauth_clientID: "{{ git_info.client_id }}"
    oauth_client_secret: "{{ git_info.client_sercret }}"
    dex_client_secret: "{{ lookup('file', '{{ output_folder_k8s }}/dex_client_secret' ) }}"
    
- name: Load template file list
  ansible.builtin.include_vars:
    file: /opt/management/index.yaml

- name: Clone a repository
  git:
    repo: '{{ tenant_repo_ssh_addr }}'
    dest: /tmp/tenant-repo
  ignore_errors: yes

- name: Copy directory to remote host excluding a subdirectory
  synchronize:
    src: /opt/management/
    dest: /tmp/tenant-repo
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=index.yaml"

- name: Generate tenant repo
  template:
    src: "/opt/management/{{ item }}"
    dest: "/tmp/tenant-repo/{{ item }}"
    mode: '0644'
  loop: "{{ templates }}"

- name: Add commit 
  shell: "cd /tmp/tenant-repo && git add . && git commit -m 'generate tenant repo'"
  ignore_errors: yes

- name: Push to remote
  shell: "cd /tmp/tenant-repo && git push"
  ignore_errors: yes
