- name: Add block of lines to /etc/hosts
  blockinfile:
    path: /etc/ssh/ssh_config
    block: |
      Host {{ gitlab_ip }}
          PasswordAuthentication yes
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          IdentityFile /root/.ssh/id_rsa
          IdentityFile {{ output_folder_gitrepo }}/tenante_repo_private.key
    state: present

- name: Git config
  shell: "git config --global user.email \"none@none.com\" &&  git config --global user.name \"none\" "

- name: Check dex client secret exists
  stat:
    path: "{{ output_folder_k8s }}/dex_client_secret"
  register: dex_client_secret_file

- name: Generate dex client secret
  copy:
    content: "{{ 1000000000 | random | to_uuid }}"
    dest: "{{ output_folder_k8s }}/dex_client_secret"
  when: not dex_client_secret_file.stat.exists

- set_fact:
    tenant_repo_id: "{{ lookup('file', '{{ output_folder_gitrepo }}/tenante_repo_id' ) }}"
    tenant_repo_ssh_addr: "{{ lookup('file', '{{ output_folder_gitrepo }}/tenante_repo_ssh_addr' ) }}"
    ca_info: "{{ lookup('file', '{{ output_folder_pki }}/ca.crt' ) }}"
    gitlab_knowhost_rsa: "{{ lookup('file', '{{ output_folder_gitrepo }}/ssh_host_rsa_key.pub' ) }}"
    gitlab_knowhost_ecdsa: "{{ lookup('file', '{{ output_folder_gitrepo }}/ssh_host_ecdsa_key.pub' ) }}"
    gitlab_knowhost_ed25519: "{{ lookup('file', '{{ output_folder_gitrepo }}/ssh_host_ed25519_key.pub' ) }}"
    oauth_clientID: "{{ lookup('file', '{{ output_folder_gitrepo }}/client_id' ) }}"
    oauth_client_secret: "{{ lookup('file', '{{ output_folder_gitrepo }}/client_sercret' ) }}"
    dex_client_secret: "{{ lookup('file', '{{ output_folder_k8s }}/dex_client_secret' ) }}"

- name: Clone a repository
  git:
    repo: '{{ tenant_repo_ssh_addr }}'
    dest: /tmp/tenant-repo
  ignore_errors: yes

- name: Create directories
  file:
    path: "/tmp/tenant-repo/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ template_path }}"
  when: 
    - "item.state == 'directory'"
    - "'.git/' not in item.path"

- name: Generate tenant repo
  template:
    src: "{{ item.src }}"
    dest: "/tmp/tenant-repo/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_community.general.filetree: "{{ template_path }}"
  when: 
    - "item.state == 'file'"
    - "'.git/' not in item.path"

- name: Copy resource to tenant repo
  copy:
    src: nautes-runtime-trigger-templates.yaml
    dest: "/tmp/tenant-repo/nautes/overlays/production/configmaps"
 
- name: Add commit 
  shell: "cd /tmp/tenant-repo && git add . && git commit -m 'generate tenant repo'"
  ignore_errors: yes

- name: Push to remote
  shell: "cd /tmp/tenant-repo && git push"
  ignore_errors: yes
