# the nautes tenant name u want
tenant_name: "nautes"

# Don't modify without knowing what you are doing
kube_entrypoint_ip: "{{ hostvars[groups['kube_control_plane'][0]].ansible_host }}"
kube_entrypoint_domain: "{{ kube_entrypoint_ip }}.nip.io"

oauth_domain: "dex.{{ kube_entrypoint_domain }}"
oauth_url: "https://{{ oauth_domain }}:31443"
oauth_source_url: "{{ gitlab_external_url }}"

gitlab_ip: "{{ hostvars[groups['gitlab'][0]].ansible_host }}"
gitlab_port: 31443
gitlab_external_url: "https://{{ gitlab_ip }}:{{ gitlab_port }}"
gitlab_ssh_addr: "ssh://git@{{ gitlab_ip }}:{{ gitlab_ssh_port }}"
gitlab_ssh_port: 22

vault_port: "8200"
vault_url: "https://{{ hostvars[groups['vault'][0]].ansible_host }}:{{ vault_port }}"
vault_proxy_url: "https://{{ hostvars[groups['vault'][0]].ansible_host }}:8000"

vcluster_api_port: 32000
nautes_api_server_domain: "apiserver.{{ kube_entrypoint_ip }}.nip.io"
argocd_api_url: "https://{{ argocd_dashboard_domain }}:31443"
argocd_dashboard_domain: "argocd.{{ kube_entrypoint_ip }}.nip.io"

output_folder: /opt/out
output_folder_pki: "{{ output_folder }}/pki"
output_folder_gitrepo: "{{ output_folder }}/git"
output_folder_hosts: "{{ output_folder }}/hosts"
output_folder_k8s: "{{ output_folder }}/kubernetes"
output_folder_secrepo: "{{ output_folder }}/vault"
output_folder_service: "{{ output_folder }}/service"

repos_tenant_template_url: https://github.com/nautes-labs/tenant-repo-template.git
repos_tenant_template_version: main
repos_cluster_template_url: https://github.com/nautes-labs/cluster-templates.git
repos_role_vault_url: https://github.com/ansible-community/ansible-vault.git
repos_role_vault_version: master
repos_role_gitlab_url: https://github.com/geerlingguy/ansible-role-gitlab.git
repos_role_gitlab_version: master

flag:
  installation:
    path: "/tmp/flags"
    name:
      host: "hosts"
      kubernetes: "k8s"
      init: "init"
      git: "gitrepo"
      tenant_repo: "tenant_repo"
      nautes: "nautes"
      secret: "secret_store"
 
nautes_namespace: nautes
nautes_secret_roles:
  api: "API"
  argo: "ARGO"
  base: "BASE"
  cluster: "CLUSTER"
  repo: "REPO"
  runtime: "RUNTIME"

