- hosts: localhost
  tasks:
  - ansible.builtin.git:
      repo: "{{ repos_tenant_template_url }}"
      dest: /opt/management
      version: "{{ repos_tenant_template_version }}"
  - ansible.builtin.git:
      repo: "{{ repos_role_vault_url }}"
      dest: /opt/nautes/roles/ansible-vault
      version: "{{ repos_role_vault_version }}"
  - ansible.builtin.git:
      repo: "{{ repos_role_gitlab_url }}"
      dest: /opt/nautes/roles/gitlab
      version: "{{ repos_role_gitlab_version }}"
 
