- name: Wait for a host to come online
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      ansible.builtin.wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        timeout: 300
        sleep: 10
      connection: local

    - name: Check whether to use apt management pack
      package_facts:
        manager: apt
    
    - name: If apt exists, execute apt upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 
      when: '"apt" in ansible_facts.packages'

