# the access info of alicloud api 
access_key: 
secret_key: 

region_id: cn-hongkong
zone_id: "{{ region_id }}-b"
instance_type: ecs.c6.large

gitlab_instance_type: "ecs.g5.large"
kubernetes_instance_type: "{{ instance_type }}"
vault_instance_type: "{{ instance_type }}"
harbor_instance_type: "{{ instance_type }}"

alicloud:
  save_money: true 

