version: "3.6"
services:
  proxy:
    image: "{{ vault_proxy_image }}"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    network_mode: "host"
    volumes:
    - "/opt/vault-proxy/configs:/data/conf"

